# Generated by Django 5.2.17 on 2026-09-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boundaries', '0002_farmlandreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_avg_c', models.FloatField(help_text='Area-weighted average temperature from the downscaled CMIP6 grid.')),
                ('precipitation_avg_mm', models.FloatField(help_text='Area-weighted average rainfall from the downscaled CMIP6 grid.')),
                ('climate_source', models.CharField(default='Downscaled/bias-corrected CMIP6 (offline pipeline, Step 4 output)', max_length=200)),
                ('pipeline_run_at', models.DateTimeField(auto_now=True)),
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='climate', to='boundaries.ward')),
            ],
        ),
    ]
