# Generated by Django 5.2.17 on 2026-09-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardclimate',
            name='period',
            field=models.CharField(blank=True, help_text='Projection period, e.g. 2026-2035.', max_length=20),
        ),
        migrations.AddField(
            model_name='wardclimate',
            name='scenario',
            field=models.CharField(blank=True, help_text='Emissions scenario, e.g. ssp245.', max_length=20),
        ),
        migrations.AlterField(
            model_name='wardclimate',
            name='precipitation_avg_mm',
            field=models.FloatField(help_text='Area-weighted annual total rainfall (mm/year) from the downscaled CMIP6 grid.'),
        ),
        migrations.AlterField(
            model_name='wardclimate',
            name='temperature_avg_c',
            field=models.FloatField(help_text='Area-weighted annual mean temperature from the downscaled CMIP6 grid.'),
        ),
    ]
