# Generated by Django 5.2.17 on 2026-09-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_pipeline', '0002_wardclimate_period_wardclimate_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardclimate',
            name='humidity_avg_pct',
            field=models.FloatField(blank=True, help_text='Annual mean relative humidity (%).', null=True),
        ),
        migrations.AddField(
            model_name='wardclimate',
            name='temperature_max_avg_c',
            field=models.FloatField(blank=True, help_text='Annual mean daily maximum temperature — heat stress matters more to crops than the mean.', null=True),
        ),
    ]
