# Generated by Django 5.2.17 on 2026-09-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0003_lgafarmland'),
        ('climate_pipeline', '0003_wardclimate_humidity_avg_pct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wardclimate',
            options={'ordering': ['period']},
        ),
        migrations.AlterField(
            model_name='wardclimate',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climates', to='boundaries.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='wardclimate',
            unique_together={('ward', 'scenario', 'period')},
        ),
    ]
