# Generated by Django 5.2.17 on 2026-09-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0004_lga_latitude_lga_longitude'),
        ('climate_pipeline', '0004_alter_wardclimate_options_alter_wardclimate_ward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGAClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_avg_c', models.FloatField()),
                ('precipitation_avg_mm', models.FloatField()),
                ('temperature_max_avg_c', models.FloatField(blank=True, null=True)),
                ('humidity_avg_pct', models.FloatField(blank=True, null=True)),
                ('climate_source', models.CharField(default='', max_length=200)),
                ('scenario', models.CharField(blank=True, max_length=20)),
                ('period', models.CharField(blank=True, max_length=20)),
                ('pipeline_run_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climates', to='boundaries.lga')),
            ],
            options={
                'ordering': ['period'],
                'unique_together': {('lga', 'scenario', 'period')},
            },
        ),
    ]
