# Generated by Django 5.2.17 on 2026-09-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lgas",
                        to="boundaries.state",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("state", "name")},
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "lga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="boundaries.lga",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("lga", "name")},
            },
        ),
        migrations.CreateModel(
            name="WardFarmland",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_agric_land", models.BooleanField()),
                (
                    "cropland_percent",
                    models.FloatField(
                        help_text="Percent of ward area classified as Cropland by ESA WorldCover."
                    ),
                ),
                (
                    "threshold_used",
                    models.FloatField(
                        default=10.0,
                        help_text="Cropland %% threshold applied to derive has_agric_land.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="ESA WorldCover (satellite-derived, auto-generated)",
                        help_text="Shown to users for transparency — this is not manually verified.",
                        max_length=100,
                    ),
                ),
                (
                    "manually_corrected",
                    models.BooleanField(
                        default=False,
                        help_text="True once a reported error has been manually flipped.",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "ward",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmland",
                        to="boundaries.ward",
                    ),
                ),
            ],
        ),
    ]
