# Generated by Django 5.2.17 on 2026-09-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0002_farmlandreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGAFarmland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_agric_land', models.BooleanField()),
                ('cropland_percent', models.FloatField(help_text='Percent of LGA area classified as Cropland by ESA WorldCover.')),
                ('threshold_used', models.FloatField(default=10.0)),
                ('source', models.CharField(default='ESA WorldCover (satellite-derived, auto-generated)', max_length=100)),
                ('manually_corrected', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('lga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmland', to='boundaries.lga')),
            ],
        ),
    ]
