# Generated by Django 5.2.17 on 2026-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0003_lgafarmland'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lga',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
